title: Aayush Khosla
logo: 56314525-57f0-4a26-b9a3-e8ca1e2359ff.jpeg
description: About me: I'm Aayush Khosla, an aspiring cricketer with a passion for tech and innovation. I love diving into the latest gadgets and exploring how tech is changing the world. Always eager to learn, push boundaries, and see where both cricket and technology take me. 
show_downloads: true
theme: jekyll-theme-minimal

